name: Cypress Tests with Dependency and Artifact Caching

on: push

jobs:
  install:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install Dependencies
        run: npm install
        working-directory: ./Cypress AUTOMATION-cctp/package.json
      
      - name: Build Project
        run: npm run build
        working-directory: ./Cypress AUTOMATION-cctp/package.json

      - name: Print working directory
        run: pwd

      - name: List files
        run: ls -la

      - name: Make scripts executable
        run: chmod +x pngtobase64.js cypress/master.js

      - name: Run imgtobase64 script
        run: node pngtobase64.js

      - name: Run readssinfo script
        run: node ./cypress/master.js

      - name: Update screenshots in repository
        run: |
          git config --global user.email "lmillaccnt@gmail.com"
          git config --global user.name "LmillCI"
          git add cypress/screenshots
          git commit -m "Update screenshots"
          git push origin master

      - name: Upload screenshots artifact
        uses: actions/upload-artifact@v4.3.5
        with:
          name: save-screenshots
          if-no-files-found: error
          path: ./cypress/screenshots

      - name: Update master json in repository
        run: |
          git config --global user.email "lmillaccnt@gmail.com"
          git config --global user.name "LmillCI"
          git add ./cypress
          git commit -m "Update masterjson"
          git push origin master

      - name: Upload master json
        uses: actions/upload-artifact@v4.3.5
        with:
          name: master json
          if-no-files-found: error
          path: ./cypress

  cypress-run:
    runs-on: ubuntu-22.04
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download the build folder
        uses: actions/download-artifact@v4
        with:
          name: save-screenshots
          path: ./cypress/screenshots
